version: '3.8'

services:
  centos7:
    image: pycontribs/centos:7
    container_name: centos7
    command: /bin/sleep 99999999
  debian:
    image: pycontribs/debian:latest
    container_name: debian
    command: /bin/sleep 99999999
  fedora:
    image: pycontribs/fedora:latest
    container_name: fedora
    command: /bin/sleep 99999999
